version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
  check-formatting:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npx prettier --check .
          name: Run prettier

workflows:
  test:
    jobs:
      - test
  check-formatting:
    jobs:
      - check-formatting
